version: "3.9"

services:
  minio:
    restart: always
    build: minio
    ports:
      - "9000:9000"
      - "9001:9001"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - minio


